### ISSUE TITLE
외부에서 인스턴스 생성 가능성이 있습니다.

### ISSUE THREAD

**Issue by Mindohyeon** [PLREQ/PLREQ#119]
## Description

<img width="534" alt="스크린샷 2023-04-03 오후 3 10 39" src="https://user-images.githubusercontent.com/81687906/229425459-e4156323-26d1-427c-9c0c-a82c0f897418.png">
현재 싱글톤 패턴으로 PLREQDataManager 인스턴스를 공유하고 있는데, 외부에서 새로운 인스턴스를 생성할 수 있습니다.<br>
이로 인해 싱글톤 패턴의 장점을 잃을 수 있으므로 외부에서 인스턴스를 생성할 수 없도록 막아야 합니다.

**Comment by Juhwa-Lee1023** [comment]
제가 최근에 바빴어서 이제 확인했네요...
맞아요!! 예리하시네요 ㅎㅎ 바로 수정해보도록 할게요!

**Comment by yeniful** [comment]
저희 앱에 관심을 갖고 이슈 만들어주셔서 감사해요! 해당 이슈 관련해서 PR 올리도록 하겠습니다😀

**Comment by Mindohyeon** [comment]
도움이 되었다니 다행입니다 ☺️
