### ISSUE TITLE
[Bug] 플레크는 세로모드만 지원합니다.

### ISSUE THREAD

**Issue by LeeSungNo-ian** [PLREQ/PLREQ#46]
## Description
- PLREQ는 세로모드만 지원합니다.
  - 가로모드를 사용했을 때, 의도하지 않은 UI가 보여집니다.
  - 기획단대로 PLREQ 는 세로모드만 지원하도록 합니다.
  
<img width="903" alt="image" src="https://user-images.githubusercontent.com/78950704/196417093-8e3cae54-198e-4373-a03a-3f7e1f3758b1.png">

## Tasks
 - [ ]  PLREQ는 오직 세로모드만 지원합니다.

**Comment by Juhwa-Lee1023** [comment]
다크 모드 기능도 같이 넣어주실 수 있으신가요~
