### ISSUE TITLE
[Feat] 앨범 커버 불러오는 방식 변경

### ISSUE THREAD

**Issue by Juhwa-Lee1023** [PLREQ/PLREQ#55]
## Description
- 앨범 커버 불러오는 방식 변경 방법

## Tasks
 - [ ]  

아니면 다른 방법도 있을 것 같아요! Kingfisher 를 사용하여 대기 중인 이미지 처리를 해주는 건 어떨까요?
_Originally posted by @LeeSungNo-ian in https://github.com/PLREQ/PLREQ/pull/54#pullrequestreview-1147650358_

**Comment by Juhwa-Lee1023** [comment]
이안 의견도 좋지만 사용자가 앱을 이용하면서 플레이리스트를 조회할때마다 이미지가 로드 되는 모습을 보는 것이 사용자에게 좋지 않을 수도 있겠다는 생각이 듭니다..!

**Comment by LeeSungNo-ian** [comment]
<img width="855" alt="image" src="https://user-images.githubusercontent.com/78950704/196728086-832c5ebc-f1e3-4931-8793-5a6bb717a084.png">

**Comment by LeeSungNo-ian** [comment]
번외로, 새로운 노래를 검색 했을 때 앨범 이미지를 받아오는데 걸리는 시간이 있을 것 같아요!
그런 경우에 KingFisher 는 대응할 수 있을 것 같다는 생각이 들었어요! 🤔

그래서 어차피 KingFisher 가 필요할 것이다..? 라는게 제 의견입니다!

**Comment by Juhwa-Lee1023** [comment]
동의합니다! 사진을 제일 처음 불러올 때에도 시간이 소요되니 좋은 생각인것 같습니다!
